- Se agrego la logica de las validaciones.  - Falta Probar  - Falta Agregar la logica de la creacion del archivo APAGAR.TXT

diff --git a/src/comandos/feprima b/src/comandos/feprima
--- a/src/comandos/feprima
+++ b/src/comandos/feprima
@@ -1,6 +1,244 @@
 #!/bin/bash
 
-echo "se ejecuto feprima"
-sleep 10
+#Valores de Retorno
+OK=0
+FEPRIMA_YA_INICIADO=1
+NO_HAY_ARCHIVOS=2
+AMBIENTE_NO_INICIALIZADO=3
 
- 
+#Constantes de validacion
+VAL_OK="1"
+VAR_ERROR="0"
+
+# Inicializo el codigo de retorno
+returncode=$OK
+
+#verifico si feprima se esta ejecutando
+cant=`expr $(ps -ef | grep "feprima" | grep $USER | grep -v grep | wc -l)`
+# Si no se esta ejecutando feprima.
+if [ $cant -eq 3 ]; then
+  #Verifico que el ambiente se encuentre incializado
+  if [ $GRUPO ]; then
+    echo "FEPRIMA - El ambiente esta incializado correctamente"
+    #Obtengo al cantidad de archivos a procesar
+    cant=`expr $(ls $PATH_FACT_RECIBIDAS | wc -l)`
+    #Si la cantidad de archivos > 0 => recorro y valido los archivos
+    if [ $cant -gt 0 ]; then
+      echo "FEPRIMA - Hay $cant archivos en el directorio $PATH_FACT_RECIBIDAS"
+      #Inicializo el archivo de log
+      glog "feprima" "Inicio de feprima" $cant "I"
+      #Recorro todos los archivos del directorio de facturas recibidas
+      for archivo in `ls $PATH_FACT_RECIBIDAS`
+      do
+        glog "feprima" "Archivo a procesar" $archivo "I"
+	echo "FEPRIMA - procesando archivo $archivo"
+	#Verifico que no sea un CAE duplicado
+	cant=`expr $(ls $PATH_FACT_ACEPTADAS/$archivo | wc -l)`
+	if [ $cant -eq 0 ]; then
+	  echo "FEPRIMA - El archivo $archivo no esta duplicado"
+	  let nroLinea=0
+          #Totales del encabezado
+          importeGravado=0.0
+          importeNoGravado=0.0
+          importeTributoIVA=0.0
+          #Totales a acumlar por el detalle de la factura
+	  montoItemGravados=0.0
+	  montoItemNoGravados=0.0
+	  montoIVAItem=0.0
+
+	  #El archivo no esta duplicado => recorro y valido el archivo
+	  for linea in $(cat $PATH_FACT_RECIBIDAS/$archivo)
+	  do
+	    val=$VAL_ERROR
+	    let nroLinea$nroLinea+1
+	    #Si estoy en el registro cabecera
+	    if [ $nroLinea -eq 1 ]; then
+              #---------------------------
+              #Valido el registro cabecera
+              #---------------------------
+	      #Valido el formato del registro cabecera
+	      echo "FEPRIMA - Cabecera a validar: $linea"
+	      val=`echo "$linea" | sed "s/^[0-9]\{11\};[ABCE];[0-9]\{4\};[0-9]\{8\};\([0-9]\{4\}-[0-1][0-9]-[0-31];\)\{2\}\([0-9]*\.[0-9]\{2\};\)\{3\}[0-9]*\.[0-9]\{2\}$/1/"
+	      	
+	      if [ "$val = $VAL_OK" ]; then
+		echo "FEPRIMA - Formato cabecera valido ($archivo)"
+		#Valido que el proveedor existe en el archivo de proveedores
+		#Obtengo el CUIT del proveedor
+		cuit=`echo "$linea" | sed "s/^\([0-9]\{11\}\);.*/\1/"`
+		#Busco el CUIT en el archivo de proveedores
+		cant=`expr $(grep "[^;];[^;];^$cuit;"  | wc -l)`
+		
+		if [ $cant -gt 0 ]
+		  echo "FEPRIMA - Proveedor encontrado CUIT: $cuit ($archivo)"
+		  #Valido que el CAE no este vencido
+		  fechaVencCAE=`echo "$linea" | sed "s/^\([^;];\)\{5\}\([^;];)\.*$/\2/"`
+		  fechaAux=`echo "$fechaVencCAE" | sed "s/^\([0-9][0-9][0-9][0-9]\)-\([0-9][0-9]\)-\([0-9][0-9]\)/\1\2\3"`	    
+                  #valido mayor a hoy
+                  fecActual=`date +%s`
+                  fecAux2=`date -d$fechaAux +%s`
+                  dif=`expr $fecActual - $fecAux2`
+                  if [ $dif -gt 0 ]; then
+	            echo "FEPRIMA - Error: $fecha es una fecha menor al dia de hoy"
+                    val=$VAL_ERROR
+                  else
+		    echo "FEPRIMA - la fecha de vencimiento CAE es correcta"
+		    val=$VAL_OK
+                  fi
+                else
+		  echo "FEPRIMA - Error: No se encuentra el al proveedor en el archivo de proveedores con CUIT: $cuit"
+                  val=$VAL_ERROR
+		fi
+	      else
+		echo "FEPRIMA - Error: El formato de la cabecera es incorrecto"
+	        val=$VAL_ERROR
+	      fi
+	      #verifico si todas las validaciones dieron ok
+	      if [ "$val" = "$VAL_OK" ]; then
+		#Regsitro cabecera valido
+		echo "FEPRIMA - Registro cabecera valido"
+		
+                #-------------------------------------------
+                #TODO: Obtener totales para validar al final
+                #-------------------------------------------
+                
+	      else
+	        #graba el error en el log
+                glog "feprima" "Factura Erronea en registro cabecera: $archivo" "E"
+                #paso al siguiente archivo
+                break; 
+	      fi
+	    else
+              #-----------------------------
+              #Valido el registro de detalle
+              #-----------------------------
+	      #Valido el formato del registro de detalle
+	      echo "FEPRIMA - Detalle a validar: $linea"
+	      val=`echo "$linea" | sed "s/^[^;];\([0-9]\{2\}\.[0-9]\{2\};\)\{2\}[0-9]\{2\}\.[0-9]\{2\}\$/1/"
+
+              if [ "$val" = "$VAL_OK" ]; then
+                echo "FEPRIMA - Formato de registro correcto"
+		#obtengo los montos
+                precio=`$(echo $linea | sed "s/^[^;];\([0-9]\{2\}\.[0-9]\{2\}\);.*$/\1/" | bc)`
+                tasaIVA=`$(echo $linea | sed "s/^[^;];[^;];\([0-9]\{2\}\.[0-9]\{2\}\);.*$/\1/" | bc)`
+                montoIVA=`$(echo $linea | sed "s/^[^;];[^;];[^;];\([0-9]\{2\}\.[0-9]\{2\}\)$/\1/" | bc)`
+
+                #Valido que los montos sean > 0
+		valPrecio=`$(echo "$precio > 0" | bc)`
+		valTasaIVA=`$(echo "$tasaIVA > 0" | bc)`
+		valMontoIVA=`$(echo "$montoIVA > 0" | bc)`
+      
+	        if [ $valPrecio -eq 1 -a $valTasaIVA -eq 1 -a $valMontoIVA -eq 1 ]; then
+	          echo "FEPRIMA - Los montos son validos"
+	          #Valido MontoIVAItem  = MontoItem * TasaIVAItem /100
+	          val=$VAL_OK
+	          montoIvaItemAux=$(echo "$precio*$tasaIVA/100" | bc)
+	          if [ $(echo "$montoIVAItemAux = $montoIVA" | bc) -eq 1 ]; then
+                    echo "FEPRIMA - MontoIVAItem correcto"
+                    val=$VAL_OK
+                    #actualizo los totales de la factura
+	            montoIVAItem=$(echo "$montoIVAItem+$montoIVA" | bc)
+                    if [ $tasaIVA -eq 0.0 ]; then
+                      #Producto no gravado
+   	              montoItemNoGravados=$(echo "$montoItemNoGravados+$precio" | bc)
+   	            else
+   	              #Producto gravado
+               	      montoItemGravados=$(echo "$montoItemGravados+$precio" | bc)
+                    fi
+	          else
+                    echo "FEPRIMA - MontoIVAItem incorrecto"
+                    val=$VAL_ERROR
+	          fi
+	        else
+                  echo "FEPRIMA - Alguno de los montos es invalido (es igual a 00.00)"
+	          val=$VAL_ERROR
+	        fi
+              else
+                echo "FEPRIMA - Formato del registro detalle incorrecto"
+                val=$VAL_ERROR
+              fi
+             
+	      #verifico si todas las validaciones dieron ok
+	      if [ "$val" = "$VAL_OK" ]; then
+		#Regsitro detalle valido
+		echo "FEPRIMA - registro detalle valido"
+	      else
+	        #archivo con errores en detalle
+                glog "feprima" "Factura Erronea en registro de Item: $archivo" "E"
+                #paso al siguiente archivo
+                break; 
+	      fi
+	    fi
+	  done
+	  if [ val = $VAL_OK ]; then
+            #------------------
+  	    #Valido los totales
+            #------------------
+	    valMontoGravado=`$(echo "$importeGravado != $montoItemGravados" | bc)`
+            if [ $valMontoGravado -eq 1 ]; then
+              echo "FEPRIMA - La suma de los MontoItem gravados es correcta (coincide con ImporteGravado de la cabecera)" 
+              val=$VAL_OK
+	      valMontoNoGravado=`$(echo "$importeNoGravado != $montoItemNoGravados" | bc)`
+              if [ $valMontoNoGravado -eq 1 ]; then
+                echo "FEPRIMA - La suma de los MontoItem no gravados es correecta (coincide con ImporteNoGravado de la cabecera)" 
+                val=$VAL_OK
+		valMontoIVAItem=`$(echo "$importeTributoIVA != $montoIVAItem" | bc)`
+                if [ $valMontoIVAItem -eq 1 ]; then
+                  echo "FEPRIMA - La suma de los montoIVAItem es correcta (coincide con ImporteTributoIVA de la cabecera)" 
+                  val=$VAL_OK
+                else
+                  echo "FEPRIMA - La suma de los montoIVAItem no coincide con ImporteTributoIVA de la cabecera" 
+                  val=$VAL_ERROR
+                  glog "feprima" "Factura Erronea no coinciden los totales: $archivo" "E"
+                fi
+              else
+                echo "FEPRIMA - La suma de los MontoItem no gravados no coincide con ImporteNoGravado de la cabecera" 
+                val=$VAL_ERROR
+                glog "feprima" "Factura Erronea no coinciden los totales: $archivo" "E"
+              fi
+            else
+              echo "FEPRIMA - La suma de los MontoItem gravados no coincide con ImporteGravado de la cabecera" 
+              val=$VAL_ERROR
+              glog "feprima" "Factura Erronea no coinciden los totales: $archivo" "E"
+            fi
+	  fi
+          #Verifico si todas las validaciones dieron OK
+          if [ "$val" = "$VAL_OK" ]; then
+          
+            #-----------------------------------
+            #TODO: Grabacion de facturas a pagar
+            #-----------------------------------
+            
+            #paso todas las validaciones
+            #muevo el archivo a aceptados
+            mover $PATH_FACT_RECIBIDAS/$archivo $PATH_FACT_ACEPTADAS/$archivo
+            #Grabo en log
+	    glog "feprima" "Factura Aceptada: $archivo" "I"
+	  else
+            #archivo con errores
+            mover $PATH_FACT_RECIBIDAS/$archivo $PATH_FACT_RECHAZADAS/$archivo
+	  fi
+	else
+	  #El archivo esta duplicado => lo muevo al directorio de rechazados
+	  mover $PATH_FACT_RECIBIDAS/$archivo $PATH_FACT_RECHAZADAS/$archivo
+	  #grabo en LOG
+	  glog "feprima" "Factura Duplicada: $archivo" "W"
+	fi
+      done
+
+      #Grabo en log
+      glog "feprima" "Fin de feprima"
+    else 
+      echo "FEPRIMA - no hay archivos para procesar en $PATH_FACT_ACEPTADAS"
+      returncode=$NO_HAY_ARCHIVOS
+    fi   
+  else
+    returncode=$AMBIENTE_NO_INICIALIZADO
+    echo "FEPRIMA - No se peude iniciar feprima porque el ambiente no esta inicializado"
+  fi
+else 
+  # Ya se estaba ejecutando
+  echo "FEPRIMA - No se puede iniciar feprima pues ya está el proceso corriendo"
+  returncode=$FEPRIMA_INICIADO
+fi
+
+exit $returncode
